# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Walter Codes
description: > # this means to ignore newlines until "baseurl:"
  I write code. I also write about code. Sometimes I even talk about it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.waltercodes.com" # the base hostname & protocol for your site
twitter_username: waltercodes
github_username:  waltercodes

# Build settings
markdown: kramdown
